/**
 * generated by Xtext 2.34.0
 */
package willburden.hale.hale.impl;

import org.eclipse.emf.ecore.EClass;

import willburden.hale.hale.HalePackage;
import willburden.hale.hale.VoidLiteral;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Void Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class VoidLiteralImpl extends LiteralImpl implements VoidLiteral
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VoidLiteralImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HalePackage.Literals.VOID_LITERAL;
  }

} //VoidLiteralImpl
