/*
 * generated by Xtext 2.34.0
 */
package willburden.hale;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class HaleStandaloneSetup extends HaleStandaloneSetupGenerated {

	public static void doSetup() {
		new HaleStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
