/*
 * generated by Xtext 2.34.0
 */
package willburden.hale.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class HaleUiModule extends AbstractHaleUiModule {

	public HaleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
