/*
 * generated by Xtext 2.34.0
 */
package willburden.hale.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class HaleScopeProvider extends AbstractHaleScopeProvider {

}
