/*
 * generated by Xtext 2.34.0
 */
package willburden.hale.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import willburden.hale.ide.contentassist.antlr.internal.InternalHaleParser;
import willburden.hale.services.HaleGrammarAccess;

public class HaleParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(HaleGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, HaleGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getBlockAccess().getAlternatives_1(), "rule__Block__Alternatives_1");
			builder.put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
			builder.put(grammarAccess.getStatementAccess().getAlternatives_3_0(), "rule__Statement__Alternatives_3_0");
			builder.put(grammarAccess.getExpression7Access().getAlternatives_1(), "rule__Expression7__Alternatives_1");
			builder.put(grammarAccess.getExpression6Access().getAlternatives_1(), "rule__Expression6__Alternatives_1");
			builder.put(grammarAccess.getExpression5Access().getAlternatives_1(), "rule__Expression5__Alternatives_1");
			builder.put(grammarAccess.getExpression4Access().getAlternatives_1(), "rule__Expression4__Alternatives_1");
			builder.put(grammarAccess.getExpression3Access().getAlternatives_1(), "rule__Expression3__Alternatives_1");
			builder.put(grammarAccess.getExpression1Access().getAlternatives(), "rule__Expression1__Alternatives");
			builder.put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
			builder.put(grammarAccess.getLiteralAccess().getAlternatives(), "rule__Literal__Alternatives");
			builder.put(grammarAccess.getHaleAccess().getGroup(), "rule__Hale__Group__0");
			builder.put(grammarAccess.getBlockAccess().getGroup(), "rule__Block__Group__0");
			builder.put(grammarAccess.getStatementAccess().getGroup_3(), "rule__Statement__Group_3__0");
			builder.put(grammarAccess.getBracedBlockAccess().getGroup(), "rule__BracedBlock__Group__0");
			builder.put(grammarAccess.getExpression7Access().getGroup(), "rule__Expression7__Group__0");
			builder.put(grammarAccess.getExpression7Access().getGroup_1_0(), "rule__Expression7__Group_1_0__0");
			builder.put(grammarAccess.getExpression7Access().getGroup_1_1(), "rule__Expression7__Group_1_1__0");
			builder.put(grammarAccess.getExpression6Access().getGroup(), "rule__Expression6__Group__0");
			builder.put(grammarAccess.getExpression6Access().getGroup_1_0(), "rule__Expression6__Group_1_0__0");
			builder.put(grammarAccess.getExpression6Access().getGroup_1_1(), "rule__Expression6__Group_1_1__0");
			builder.put(grammarAccess.getExpression5Access().getGroup(), "rule__Expression5__Group__0");
			builder.put(grammarAccess.getExpression5Access().getGroup_1_0(), "rule__Expression5__Group_1_0__0");
			builder.put(grammarAccess.getExpression5Access().getGroup_1_1(), "rule__Expression5__Group_1_1__0");
			builder.put(grammarAccess.getExpression5Access().getGroup_1_2(), "rule__Expression5__Group_1_2__0");
			builder.put(grammarAccess.getExpression5Access().getGroup_1_3(), "rule__Expression5__Group_1_3__0");
			builder.put(grammarAccess.getExpression4Access().getGroup(), "rule__Expression4__Group__0");
			builder.put(grammarAccess.getExpression4Access().getGroup_1_0(), "rule__Expression4__Group_1_0__0");
			builder.put(grammarAccess.getExpression4Access().getGroup_1_1(), "rule__Expression4__Group_1_1__0");
			builder.put(grammarAccess.getExpression3Access().getGroup(), "rule__Expression3__Group__0");
			builder.put(grammarAccess.getExpression3Access().getGroup_1_0(), "rule__Expression3__Group_1_0__0");
			builder.put(grammarAccess.getExpression3Access().getGroup_1_1(), "rule__Expression3__Group_1_1__0");
			builder.put(grammarAccess.getExpression3Access().getGroup_1_2(), "rule__Expression3__Group_1_2__0");
			builder.put(grammarAccess.getExpression2Access().getGroup(), "rule__Expression2__Group__0");
			builder.put(grammarAccess.getExpression2Access().getGroup_1(), "rule__Expression2__Group_1__0");
			builder.put(grammarAccess.getExpression1Access().getGroup_0(), "rule__Expression1__Group_0__0");
			builder.put(grammarAccess.getExpression1Access().getGroup_1(), "rule__Expression1__Group_1__0");
			builder.put(grammarAccess.getPrimaryAccess().getGroup_2(), "rule__Primary__Group_2__0");
			builder.put(grammarAccess.getBindingAccess().getGroup(), "rule__Binding__Group__0");
			builder.put(grammarAccess.getAssignmentAccess().getGroup(), "rule__Assignment__Group__0");
			builder.put(grammarAccess.getPrintAccess().getGroup(), "rule__Print__Group__0");
			builder.put(grammarAccess.getIfAccess().getGroup(), "rule__If__Group__0");
			builder.put(grammarAccess.getIfAccess().getGroup_3(), "rule__If__Group_3__0");
			builder.put(grammarAccess.getIfAccess().getGroup_4(), "rule__If__Group_4__0");
			builder.put(grammarAccess.getWhileAccess().getGroup(), "rule__While__Group__0");
			builder.put(grammarAccess.getHaleAccess().getBlockAssignment_1(), "rule__Hale__BlockAssignment_1");
			builder.put(grammarAccess.getBlockAccess().getStatementsAssignment_1_0(), "rule__Block__StatementsAssignment_1_0");
			builder.put(grammarAccess.getExpression7Access().getRightAssignment_1_0_2(), "rule__Expression7__RightAssignment_1_0_2");
			builder.put(grammarAccess.getExpression7Access().getRightAssignment_1_1_2(), "rule__Expression7__RightAssignment_1_1_2");
			builder.put(grammarAccess.getExpression6Access().getRightAssignment_1_0_2(), "rule__Expression6__RightAssignment_1_0_2");
			builder.put(grammarAccess.getExpression6Access().getRightAssignment_1_1_2(), "rule__Expression6__RightAssignment_1_1_2");
			builder.put(grammarAccess.getExpression5Access().getRightAssignment_1_0_2(), "rule__Expression5__RightAssignment_1_0_2");
			builder.put(grammarAccess.getExpression5Access().getRightAssignment_1_1_2(), "rule__Expression5__RightAssignment_1_1_2");
			builder.put(grammarAccess.getExpression5Access().getRightAssignment_1_2_2(), "rule__Expression5__RightAssignment_1_2_2");
			builder.put(grammarAccess.getExpression5Access().getRightAssignment_1_3_2(), "rule__Expression5__RightAssignment_1_3_2");
			builder.put(grammarAccess.getExpression4Access().getRightAssignment_1_0_2(), "rule__Expression4__RightAssignment_1_0_2");
			builder.put(grammarAccess.getExpression4Access().getRightAssignment_1_1_2(), "rule__Expression4__RightAssignment_1_1_2");
			builder.put(grammarAccess.getExpression3Access().getRightAssignment_1_0_2(), "rule__Expression3__RightAssignment_1_0_2");
			builder.put(grammarAccess.getExpression3Access().getRightAssignment_1_1_2(), "rule__Expression3__RightAssignment_1_1_2");
			builder.put(grammarAccess.getExpression3Access().getRightAssignment_1_2_2(), "rule__Expression3__RightAssignment_1_2_2");
			builder.put(grammarAccess.getExpression2Access().getRightAssignment_1_2(), "rule__Expression2__RightAssignment_1_2");
			builder.put(grammarAccess.getExpression1Access().getInnerAssignment_0_2(), "rule__Expression1__InnerAssignment_0_2");
			builder.put(grammarAccess.getExpression1Access().getInnerAssignment_1_2(), "rule__Expression1__InnerAssignment_1_2");
			builder.put(grammarAccess.getNumberLiteralAccess().getValueAssignment(), "rule__NumberLiteral__ValueAssignment");
			builder.put(grammarAccess.getStringLiteralAccess().getValueAssignment(), "rule__StringLiteral__ValueAssignment");
			builder.put(grammarAccess.getBindingAccess().getMutableAssignment_1(), "rule__Binding__MutableAssignment_1");
			builder.put(grammarAccess.getBindingAccess().getNameAssignment_2(), "rule__Binding__NameAssignment_2");
			builder.put(grammarAccess.getBindingAccess().getExpressionAssignment_4(), "rule__Binding__ExpressionAssignment_4");
			builder.put(grammarAccess.getBindingReferenceAccess().getBindingAssignment(), "rule__BindingReference__BindingAssignment");
			builder.put(grammarAccess.getAssignmentAccess().getBindingAssignment_0(), "rule__Assignment__BindingAssignment_0");
			builder.put(grammarAccess.getAssignmentAccess().getExpressionAssignment_2(), "rule__Assignment__ExpressionAssignment_2");
			builder.put(grammarAccess.getPrintAccess().getExpressionAssignment_1(), "rule__Print__ExpressionAssignment_1");
			builder.put(grammarAccess.getIfAccess().getConditionsAssignment_1(), "rule__If__ConditionsAssignment_1");
			builder.put(grammarAccess.getIfAccess().getIfBlocksAssignment_2(), "rule__If__IfBlocksAssignment_2");
			builder.put(grammarAccess.getIfAccess().getConditionsAssignment_3_1(), "rule__If__ConditionsAssignment_3_1");
			builder.put(grammarAccess.getIfAccess().getIfBlocksAssignment_3_2(), "rule__If__IfBlocksAssignment_3_2");
			builder.put(grammarAccess.getIfAccess().getElseBlockAssignment_4_1(), "rule__If__ElseBlockAssignment_4_1");
			builder.put(grammarAccess.getWhileAccess().getConditionAssignment_1(), "rule__While__ConditionAssignment_1");
			builder.put(grammarAccess.getWhileAccess().getBlockAssignment_2(), "rule__While__BlockAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private HaleGrammarAccess grammarAccess;

	@Override
	protected InternalHaleParser createParser() {
		InternalHaleParser result = new InternalHaleParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public HaleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(HaleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
