/*
 * generated by Xtext 2.34.0
 */
package willburden.hale.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import willburden.hale.HaleRuntimeModule;
import willburden.hale.HaleStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class HaleIdeSetup extends HaleStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new HaleRuntimeModule(), new HaleIdeModule()));
	}
	
}
