/**
 * generated by Xtext 2.34.0
 */
package willburden.hale.hale;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Application</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link willburden.hale.hale.Application#getExpression <em>Expression</em>}</li>
 *   <li>{@link willburden.hale.hale.Application#getArguments <em>Arguments</em>}</li>
 * </ul>
 *
 * @see willburden.hale.hale.HalePackage#getApplication()
 * @model
 * @generated
 */
public interface Application extends Expression
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Expression)
   * @see willburden.hale.hale.HalePackage#getApplication_Expression()
   * @model containment="true"
   * @generated
   */
  Expression getExpression();

  /**
   * Sets the value of the '{@link willburden.hale.hale.Application#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Expression value);

  /**
   * Returns the value of the '<em><b>Arguments</b></em>' containment reference list.
   * The list contents are of type {@link willburden.hale.hale.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arguments</em>' containment reference list.
   * @see willburden.hale.hale.HalePackage#getApplication_Arguments()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getArguments();

} // Application
