/**
 * generated by Xtext 2.34.0
 */
package willburden.hale.hale;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Binding Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link willburden.hale.hale.BindingReference#getBinding <em>Binding</em>}</li>
 * </ul>
 *
 * @see willburden.hale.hale.HalePackage#getBindingReference()
 * @model
 * @generated
 */
public interface BindingReference extends Expression
{
  /**
   * Returns the value of the '<em><b>Binding</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Binding</em>' reference.
   * @see #setBinding(Binding)
   * @see willburden.hale.hale.HalePackage#getBindingReference_Binding()
   * @model
   * @generated
   */
  Binding getBinding();

  /**
   * Sets the value of the '{@link willburden.hale.hale.BindingReference#getBinding <em>Binding</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Binding</em>' reference.
   * @see #getBinding()
   * @generated
   */
  void setBinding(Binding value);

} // BindingReference
