/**
 * generated by Xtext 2.34.0
 */
package willburden.hale.hale;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see willburden.hale.hale.HalePackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends Statement
{
} // Expression
