/**
 * generated by Xtext 2.34.0
 */
package willburden.hale.hale;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hale</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link willburden.hale.hale.Hale#getMainBlock <em>Main Block</em>}</li>
 * </ul>
 *
 * @see willburden.hale.hale.HalePackage#getHale()
 * @model
 * @generated
 */
public interface Hale extends EObject
{
  /**
   * Returns the value of the '<em><b>Main Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Main Block</em>' containment reference.
   * @see #setMainBlock(Block)
   * @see willburden.hale.hale.HalePackage#getHale_MainBlock()
   * @model containment="true"
   * @generated
   */
  Block getMainBlock();

  /**
   * Sets the value of the '{@link willburden.hale.hale.Hale#getMainBlock <em>Main Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Main Block</em>' containment reference.
   * @see #getMainBlock()
   * @generated
   */
  void setMainBlock(Block value);

} // Hale
