/**
 * generated by Xtext 2.34.0
 */
package willburden.hale.hale;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hale</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link willburden.hale.hale.Hale#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see willburden.hale.hale.HalePackage#getHale()
 * @model
 * @generated
 */
public interface Hale extends EObject
{
  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link willburden.hale.hale.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see willburden.hale.hale.HalePackage#getHale_Statements()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStatements();

} // Hale
