/**
 * generated by Xtext 2.34.0
 */
package willburden.hale.hale;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Input</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see willburden.hale.hale.HalePackage#getInput()
 * @model
 * @generated
 */
public interface Input extends Expression
{
} // Input
