/**
 * generated by Xtext 2.34.0
 */
package willburden.hale.hale;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logical Not</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link willburden.hale.hale.LogicalNot#getInner <em>Inner</em>}</li>
 * </ul>
 *
 * @see willburden.hale.hale.HalePackage#getLogicalNot()
 * @model
 * @generated
 */
public interface LogicalNot extends Expression
{
  /**
   * Returns the value of the '<em><b>Inner</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inner</em>' containment reference.
   * @see #setInner(Expression)
   * @see willburden.hale.hale.HalePackage#getLogicalNot_Inner()
   * @model containment="true"
   * @generated
   */
  Expression getInner();

  /**
   * Sets the value of the '{@link willburden.hale.hale.LogicalNot#getInner <em>Inner</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inner</em>' containment reference.
   * @see #getInner()
   * @generated
   */
  void setInner(Expression value);

} // LogicalNot
