/**
 * generated by Xtext 2.34.0
 */
package willburden.hale.hale;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Void Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see willburden.hale.hale.HalePackage#getVoidLiteral()
 * @model
 * @generated
 */
public interface VoidLiteral extends Literal
{
} // VoidLiteral
