/*
 * generated by Xtext 2.34.0
 */
package willburden.hale.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import willburden.hale.ui.internal.HaleActivator;

public class HaleUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return HaleActivator.getInstance().getInjector("willburden.hale.Hale");
	}

}
