/*
 * generated by Xtext 2.34.0
 */
package willburden.hale.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import willburden.hale.ui.internal.HaleActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HaleExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(HaleActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		HaleActivator activator = HaleActivator.getInstance();
		return activator != null ? activator.getInjector(HaleActivator.WILLBURDEN_HALE_HALE) : null;
	}

}
